name: Engine Commit Notify

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord Webhook Notification
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}  # your engine channel webhook
          repo_name: "magic-charts"
          censor_username: false
          hide_links: false
          color: 7dbbe6
          
